---
- name: Install necessary packages
  import_tasks: install.yml

- name: Configure docker
  import_tasks: configure.yml

- name: Install plugins
  import_tasks: plugins.yml

- name: Test docker
  import_tasks: test.yml
