---
- name: "Read variables"
  tags:
    - add,del,remove
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - "keys.yml"
      paths: "files/pubkeys/"

- name: "Deploy SSH-Keys to remote host"
  tags:
    - add
  ansible.posix.authorized_key:
    user: root
    key: "{{ keystodeploy|map(attribute='sshkey')|join('\n') }}"
    exclusive: true
  when: "'add' in ansible_run_tags"

- name: "Remove SSH-Keys to remote host"
  tags:
    - del,remove
  ansible.posix.authorized_key:
    user: root
    key: "{{ keystoremove|map(attribute='sshkey')|join('\n') }}"
    state: absent
  when: "'del' in ansible_run_tags"

