---
# deb Part
- when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    #- name: Copy unattended upgrade config
      #ansible.builtin.copy:
        #src: ../files/50unattended-upgrades
        #dest: /etc/apt/apt.conf.d/50unattended-upgrades
        #owner: root
        #group: root
        #mode: '0644'

    - name: Update apt-get repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    #- name: Install security updates
      #ansible.builtin.command: >
        #/usr/bin/unattended-upgrades -v

    #- name: Update all host/vm packages
      #ansible.builtin.apt:
       #update_cache: true
       #cache_valid_time: 3600
       #name: "*"
       #state: latest

    - name: Update all Debian/Ubuntu packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Check if a reboot is required
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot and wait up to 5 min
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required_file.stat.exists
      register: reboot_result

    - name: reboot time
      debug:
        msg: "{{ ansible_hostname }} rebooted in {{ reboot_result.elapsed }} seconds."

# rpm Part
- when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
  block:
    - name: Ensure all packages are up-to-date
      dnf:
        name: "*"
        state: latest
      register: update_result

    - name: Check if a reboot is needed
      shell: needs-restarting -r; echo $?
      register: reboot_needed
      changed_when: false

    - name: Reboot the server if needed
      reboot:
      when: reboot_needed.stdout != "0"

    - name: Wait up to 5 min for the server to come back online
      wait_for_connection:
        timeout: 300
      when: reboot_needed.stdout != "0"
      register: reboot_result

    - name: reboot time
      debug:
        msg: "{{ ansible_hostname }} rebooted in {{ reboot_result.elapsed }} seconds."

