#!/bin/bash
#
HOST=$(hostname)
LIST="
"
for i in $LIST; do
	docker container exec $i sh 2>/dev/null;
	if [ $? != 0 ] ; then
		export FAILED="$FAILED $i"
	fi
done

if [ ${FAILED+x} ]  ; then
	echo "$FAILED down" | mail -s "$HOST Status $(date +%d.%m.%Y) " $HOST@REDACTED
	echo "$FAILED down"
fi
