---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-populate-volumes
        image: nginx:latest
        command:
          - /bin/sh
          - -c
          - |
            # 1. Konfiguration kopieren, wenn der Ordner leer ist oder NUR lost+found enthält
            if [ ! -d /target-config ] || [ -z "$(ls -A /target-config | grep -v '^lost+found$')" ]; then
              echo "Kopiere NGINX Configs..."
              cp -a /etc/nginx/. /target-config/;
            fi
            # 2. Web-Verzeichnis kopieren, wenn der Ordner leer ist oder NUR lost+found enthält
            if [ ! -d /target-data ] || [ -z "$(ls -A /target-data | grep -v '^lost+found$')" ]; then
              echo "Kopiere Web-Daten..."
              cp -a /usr/share/nginx/html/. /target-data/;
            fi
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /target-config
        - name: nginx-data-volume
          mountPath: /target-data
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: "/etc/nginx"
        - name: nginx-data-volume
          mountPath: "/usr/share/nginx/html"
        - name: nginx-log-volume
          mountPath: "/var/log/nginx"
      volumes:
      - name: nginx-config-volume
        persistentVolumeClaim:
          claimName: nginx-config-pvc 
      - name: nginx-data-volume
        persistentVolumeClaim:
          claimName: nginx-data-pvc 
      - name: nginx-log-volume
        persistentVolumeClaim:
          claimName: nginx-log-pvc 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-pvc
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
