- name: Add user "{{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ user_password }}"
    state: present
    shell: "{{ user_shell }}"
    comment: "User only for tty login"

- name: Add user "{{ user }}" to "{{ group_name }}" group ({{ ansible_distribution }} {{ ansible_distribution_version }})
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ group_name }}"
    append: yes
  vars:
    group_name: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' if ansible_facts['os_family'] == 'RedHat' }}"
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Ensure config directory exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create SSH configuration file for denying user "{{ user }}"
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/user_deny.conf
    content: |
      # Don't allow "{{ user }}" to login with ssh
      DenyUsers "{{ user }}"
    owner: root
    group: root
    mode: '0644'

- name: Include config.d directory in main configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Include /etc/ssh/sshd_config.d/\*\.conf'
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    state: present

- name: Restart SSH service "{{ sshd_name }}" to apply changes ({{ ansible_distribution }} {{ ansible_distribution_version }})
  ansible.builtin.service:
    name: "{{ sshd_name }}"
    state: restarted
  vars:
    sshd_name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' if ansible_facts['os_family'] == 'RedHat' }}"
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

