---
- hosts: deploy
  become: true
  become_user: root
  environment:
    LC_ALL: C
    LANG: C

  pre_tasks:
    - name: "Load list of packages"
      tags:
        - deploy
        - packages
      ansible.builtin.include_vars:
        file: pkgs.yml

    - name: "Set Swap Size"
      tags:
        - deploy
        - swap
      ansible.builtin.include_vars:
        file: swap.yml

    - name: "Set User Vars"
      tags:
        - deploy
        - user
      ansible.builtin.include_vars:
        file: user.yml

  roles:
    - role: deploy
      tags: deploy
    - role: swap
      tags: swap
    - role: storagebox
      tags: storagebox
    - role: docker
      tags: docker
    - role: scripts
      tags: scripts
    - role: mail
      tags: mail
    - role: locale
      tags: locale
    - role: sshd
      tags: sshd
    - role: user
      tags: user
    - role: unattended-upgrades
      tags: unattended-upgrades
    - role: patchmanagement
    - role: checkservices
      tags: checkservices
    #- role: podman
      #tags: podman
    #- role: apache
      #tags: apache
