---
- hosts: deploy
  become: true
  become_user: root
  environment:
    LC_ALL: C
    LANG: C

  pre_tasks:
    - name: "Load list of packages"
      tags:
        - deploy
        - packages
        - pkgs
      ansible.builtin.include_vars:
        file: pkgs.yml

    - name: "Set Swap Size"
      tags:
        - deploy
        - swap
      ansible.builtin.include_vars:
        file: swap.yml

    - name: "Set User Vars"
      tags:
        - deploy
        - user
      ansible.builtin.include_vars:
        file: user.yml

    - name: "Set MAILTO"
      tags:
        - cron
        - deploy
      ansible.builtin.include_vars:
        file: cron.yml

    - name: "Set backup path"
      tags:
        - cron
        - deploy
        - docker
        - scripts
      ansible.builtin.include_vars:
        file: scripts.yml

    - name: "Set Variables for docker"
      tags:
        - docker
      ansible.builtin.include_vars:
        file: docker.yml

  roles:
    - role: deploy
      tags: deploy
    - role: cron
      tags: cron
    - role: swap
      tags: swap
    - role: locale
      tags: locale
    - role: sshd
      tags: sshd
    - role: user
      tags: user
    - role: storagebox
      tags: storagebox,rclone
    - role: docker
      tags: docker
    - role: scripts
      tags: scripts
    - role: unattended-upgrades
      tags: unattended-upgrades
    - role: mail
      tags: mail
    - role: patch
      tags: patch
    - role: checkservices
      tags: checkservices
