---
- name: Manage Docker containers
  hosts: docker_server
  become: true
  become_user: root
  environment:
    LC_ALL: C
    LANG: C
  pre_tasks:
    - name: "Set Variables"
      tags:
        - docker
        - docker-restart
      ansible.builtin.include_vars:
        file: docker.yml
  roles:
    - role: docker-stop
      tags: docker-stop,stop
    - role: docker-start
      tags: docker-start,start
    - role: docker-restart
      tags: docker-restart,restart

