---
#- name: Update packages ({{ ansible_distribution }} {{ ansible_distribution_version }})
  #ansible.builtin.package:
    #name: "*"
    #state: latest
    #update_cache: yes

# deb Part
- when: ansible_facts['os_family'] in ['Debian']
  block:
    #- name: Update apt-get repo and cache ({{ ansible_distribution }} {{ ansible_distribution_version }})
      #ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
#
    #- name: Install security updates ({{ ansible_distribution }} {{ ansible_distribution_version }})
      #ansible.builtin.command: >
        #/usr/bin/unattended-upgrades -v
#
    - name: Update all packages to their latest version ({{ ansible_distribution }} {{ ansible_distribution_version }})
      ansible.builtin.apt:
       update_cache: true
       name: "*"
       cache_valid_time: 3600
       state: latest
#
    #- name: Update all packages to their latest version ({{ ansible_distribution }} {{ ansible_distribution_version }})
      #ansible.builtin.apt:
        #name: "*"
        #state: latest

    - name: Reboot ({{ ansible_distribution }} {{ ansible_distribution_version }})
      block:
        - name: Check if a reboot is required ({{ ansible_distribution }} {{ ansible_distribution_version }})
          register: reboot_required_file
          ansible.builtin.stat:
            path: /var/run/reboot-required
            checksum_algorithm: sha1

        - name: Reboot and wait up to 5 min ({{ ansible_distribution }} {{ ansible_distribution_version }})
          ansible.builtin.reboot:
            reboot_timeout: 300
          when: reboot_required_file.stat.exists
          register: reboot_result

        - name: reboot time ({{ ansible_distribution }} {{ ansible_distribution_version }})
          debug:
            msg: "{{ ansible_hostname }} rebooted in {{ reboot_result.elapsed }} seconds."
          when: reboot_result is defined and 'elapsed' in reboot_result

# rpm Part
- when: ansible_facts['os_family'] in ['RedHat']
  block:
    - name: Install requirements ({{ ansible_distribution }} {{ ansible_distribution_version }})
      ansible.builtin.package:
        name: dnf-utils
        state: present

    - name: Update all packages to their latest version ({{ ansible_distribution }} {{ ansible_distribution_version }})
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: update_result

    - name: Reboot ({{ ansible_distribution }} {{ ansible_distribution_version }})
      block:
        - name: Check if a reboot is required ({{ ansible_distribution }} {{ ansible_distribution_version }})
          shell: needs-restarting -r; echo $?
          register: reboot_needed
          changed_when: false

        - name: List updated packages require a reboot ({{ ansible_distribution }} {{ ansible_distribution_version }})
          debug:
            msg: "{{ reboot_needed.stdout_lines }}"

        - name: Reboot the server if needed ({{ ansible_distribution }} {{ ansible_distribution_version }})
          reboot:
          when: reboot_needed.stdout != "0"

        - name: Wait up to 5 min for the server to come back online ({{ ansible_distribution }} {{ ansible_distribution_version }})
          wait_for_connection:
            timeout: 300
          when: reboot_needed.stdout != "0"
          register: reboot_result

        - name: reboot time ({{ ansible_distribution }} {{ ansible_distribution_version }})
          debug:
            msg: "{{ ansible_hostname }} rebooted in {{ reboot_result.elapsed }} seconds."

