---
- name: Install requirements ({{ ansible_distribution }} {{ ansible_distribution_version }})
  ansible.builtin.package:
    name:
      - libsasl2-modules
      - mailutils
      - postfix
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] in ['Debian']

- name: Install requirements ({{ ansible_distribution }} {{ ansible_distribution_version }})
  ansible.builtin.package:
    name:
      - cyrus-sasl-plain
      - postfix
      - s-nail
    state: present
  when: ansible_facts['os_family'] in ['RedHat']

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: /etc/postfix
    state: directory
    mode: '0755'

- name: Copy sasl_passwd
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: '0600'

- name: Copy main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'

- name: Hash password
  ansible.builtin.shell: "postmap hash:/etc/postfix/sasl_passwd"

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Send test mail
  ansible.builtin.shell: echo "Ansible has installed mail capabilities at $(date '+%D %T') on $(hostname)" | mail -s "Ansible has installed mail capabilities on $(hostname)" {{ mailAddress }}

