---
- name: Install {{ package_name }} Webserver ({{ ansible_distribution }} {{ ansible_distribution_version }})
  package:
    name: "{{ package_name }}"
    state: present
  vars:
    package_name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Debian']

- name: Restart {{ package_name }} ({{ ansible_distribution }} {{ ansible_distribution_version }})
  service:
    name: "{{ package_name }}"
    state: started
    enabled: yes
  vars:
    package_name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Debian']
