#!/bin/bash

/usr/bin/sqlite3 /var/lib/fail2ban/fail2ban.sqlite3 <<EOF
.mode column
.headers on
SELECT datetime(timeofban, 'unixepoch', 'localtime') AS BanTime,
       json_extract(data, '$.ip4') AS IPAddress,
       json_extract(data, '$.user') AS Username
FROM bans;
#SELECT json_extract(data, '$.ip4', '$.user') FROM bans;
#SELECT json_extract(data, '$.ip4', '$.user', '$.matches') FROM bans;

EOF
exit 0;

