---
# PKGS
- name: Install requirements ({{ ansible_distribution }} {{ ansible_distribution_version }})
  ansible.builtin.package:
    name:
      - "{{ fuse_name }}"
      - rclone
      - unzip
    state: present
    update_cache: yes
  vars:
    fuse_name: "{{ 'fuse3' if ansible_facts['os_family'] == 'Debian' else 'fuse' if ansible_facts['os_family'] == 'RedHat' }}"
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

#- name: Install requirements ({{ ansible_distribution }} {{ ansible_distribution_version }})
  #apt:
    #name: "{{ item }}"
    #state: latest
    #update_cache: yes
  #with_items:
    #- fuse3
    #- rclone
    #- unzip
  #when: ansible_facts['os_family'] in ['Debian']

- name: Create a symbolic link for fuser
  ansible.builtin.file:
    src: /usr/bin/fusermount
    dest: /usr/bin/fusermount3
    owner: root
    group: root
    state: link
  ignore_errors: True
  when: ansible_facts['os_family'] in ['Debian']

- name: Install latest rclone version
  ansible.builtin.shell: |
    curl https://rclone.org/install.sh | bash
  ignore_errors: True

# CFG
- name: Create /mnt/storage directory
  ansible.builtin.file:
    path: /mnt/storage
    state: directory
    mode: '0755'

- name: Create /mnt/DATA directory
  ansible.builtin.file:
    path: /mnt/DATA
    state: directory
    mode: '0755'

- name: Create /mnt/MEDIA directory
  ansible.builtin.file:
    path: /mnt/MEDIA
    state: directory
    mode: '0755'

- name: Create cache directory
  ansible.builtin.file:
    path: /var/cache/rclone
    owner: root
    group: root
    state: directory
    recurse: yes

- name: Copy rclone config
  ansible.builtin.copy:
    src: ../files/rclone.conf
    dest: /etc/rclone.conf
    owner: root
    group: root
    mode: '0644'

- name: Create a symbolic link for mount.rclone
  ansible.builtin.file:
    src: /usr/bin/rclone
    dest: /usr/sbin/mount.rclone
    owner: root
    group: root
    state: link

# MNT
- name: Mount storage
  ansible.posix.mount:
    src: 'storagebox:'
    path: /mnt/storage
    opts: rw,nofail,_netdev,args2env,vfs_cache_mode=minimal,vfs_cache_max_age=5m,config=/etc/rclone.conf,cache_dir=/var/cache/rclone
    boot: true
    state: mounted
    fstype: rclone

- name: Mount storage DATA
  tags:
    - data
  ansible.posix.mount:
    src: 'data:'
    path: /mnt/DATA
    opts: rw,nofail,_netdev,args2env,vfs_cache_mode=minimal,vfs_cache_max_size=15G,vfs_cache_max_age=5m,config=/etc/rclone.conf,cache_dir=/var/cache/rclone
    boot: true
    state: mounted
    fstype: rclone

- name: Mount storage MEDIA
  tags:
    - media
  ansible.posix.mount:
    src: 'media:'
    path: /mnt/MEDIA
    opts: rw,nofail,_netdev,args2env,vfs_cache_mode=minimal,vfs_cache_max_size=15G,vfs_cache_max_age=5m,config=/etc/rclone.conf,cache_dir=/var/cache/rclone
    boot: true
    state: mounted
    fstype: rclone

#SYS
- name: Apply changes
  ansible.builtin.command: systemctl daemon-reload

