---
- tags:
  - deploy
  - scripts
  block:
    - name: Ensure the directory {{ backup_path }} exists
      file:
        path: "{{ backup_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        recurse: True

    - name: Ensure the directory {{ scripts_path }} exists
      file:
        path: "{{ scripts_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        recurse: True

    - name: Ensure directory {{ bin_path }} exists
      ansible.builtin.file:
        path: "{{ bin_path }}"
        state: directory
        recurse: yes

    - name: Copy banned
      ansible.builtin.copy:
        src: ../files/banned
        dest: "{{ bin_path }}"
        owner: root
        group: root
        mode: '0755'

    - name: Copy spacewatch
      ansible.builtin.copy:
        src: ../files/spacewatch
        dest: "{{ bin_path }}"
        owner: root
        group: root
        mode: '0755'

    - name: Copy backup_volumes.sh
      ansible.builtin.template:
        src: backup_volumes.j2
        dest: "{{ scripts_path }}/backup_volumes.sh"
        owner: root
        group: root
        mode: '0755'

