---
# UNATTENDED-UPGRADES
#- name: Copy 50unattended-upgrades
    #- copy
  #ansible.builtin.template:
    #src: 50unattended-upgrades.j2
    #dest: /etc/apt/apt.conf.d/50unattended-upgrades
    #mode: '0644'

- when: ansible_facts['os_family'] in ['Debian']
  block:
    - name: Security updates only
      ansible.builtin.replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^\s*"\$\{distro_id\}:\$\{distro_codename\}";'
        replace: '// \g<0>'

    - name: AutoFixInterruptedDpkg
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::AutoFixInterruptedDpkg\s+".*";|^Unattended-Upgrade::AutoFixInterruptedDpkg\s+".*";'
        line: 'Unattended-Upgrade::AutoFixInterruptedDpkg "true";'

    - name: Mail
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Mail\s+".*";|Unattended-Upgrade::Mail\s+".*";'
        line: 'Unattended-Upgrade::Mail "{{ mailAddress }}";'

    - name: MailReport
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::MailReport\s+".*";|^Unattended-Upgrade::MailReport\s+".*";'
        line: 'Unattended-Upgrade::MailReport "on-change";'

    - name: Remove-Unused-Kernel-Packages
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Remove-Unused-Kernel-Packages\s+".*";|^Unattended-Upgrade::Remove-Unused-Kernel-Packages\s+".*";'
        line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'

    - name: Remove-New-Unused-Dependencies
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Remove-New-Unused-Dependencies\s+".*";|^Unattended-Upgrade::Remove-New-Unused-Dependencies\s+".*";'
        line: 'Unattended-Upgrade::Remove-New-Unused-Dependencies "true";'

    - name: Remove-Unused-Dependencies
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies\s+".*";|^Unattended-Upgrade::Remove-Unused-Dependencies\s+".*";'
        line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'

    - name: Automatic-Reboot
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Automatic-Reboot\s+".*";|^Unattended-Upgrade::Automatic-Reboot\s+".*";'
        line: 'Unattended-Upgrade::Automatic-Reboot "true";'

    - name: Automatic-Reboot-Time
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Automatic-Reboot-Time\s+".*";|^Unattended-Upgrade::Automatic-Reboot-Time\s+".*";'
        line: 'Unattended-Upgrade::Automatic-Reboot-Time "04:00";'

    - name: Apply changes
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: restarted
