- name: Gathering Facts
  ansible.builtin.setup:
    gather_subset:
      - min
      - hardware

- name: Gathering Facts of swapfile "{{ swap_file }}"
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  changed_when: false

- name: Get the list of swap files
  command: swapon -s
  register: swap_file_list
  changed_when: false

- name: Create swap file "{{ swap_file }}"
  file:
    path: "{{ swap_file }}"
    state: touch
    mode: 0600
  when: not swap_file_check.stat.exists

- name: Gathering Facts of swapfile "{{ swap_file }}"
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  changed_when: false

- name: Allocate swap file "{{ swap_file }}"
  command: fallocate -l {{ swap_space }}G {{ swap_file }}
  when: swap_file_check.stat.exists and swap_file_check.stat.size == 0

- name: Gathering Facts of swapfile "{{ swap_file }}"
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  changed_when: false

- name: Zeroing swap space "{{ swap_file }}"
  command: dd if=/dev/zero of={{ swap_file }} bs=1G count={{ swap_space }}
  when:
  - swap_file_check.stat.exists
  - swap_file_check.stat.size > 0
  - swap_file not in swap_file_list.stdout

- name: Gathering Facts of swapfile "{{ swap_file }}"
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  changed_when: false

- name: Format swap file "{{ swap_file }}"
  command: mkswap {{ swap_file }}
  when: swap_file_check.stat.exists and swap_file_check.stat.size > 0 and not swap_file in swap_file_list.stdout

- name: Add "{{ swap_file }}" to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: Set permissions on swap file "{{ swap_file }}"
  file:
    path: "{{ swap_file }}"
    mode: 0600
  when: swap_file_check.stat.exists and swap_file_check.stat.size > 0 and swap_file_check.stat.mode != "0600"

- name: Turn on swap
  command: swapon -a
  when: swap_file_check.stat.size > 0 and swap_file_check.stat.mode == "0600"  and not swap_file in swap_file_list.stdout

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"

- name: Refresh facts
  ansible.builtin.setup:
    gather_subset:
      - min
      - hardware

- name: Calculate file size in GB
  set_fact:
    file_size_gb: "{{ (swap_file_check.stat.size | float / 1000000000) | round(0) | int }}"

- name: Calculate total swap size in GB
  set_fact:
    swap_total_gb: "{{ (ansible_swaptotal_mb | float / 1000) | round(0) | int }}"

- name: Display file size of "{{ swap_file }}"
  debug:
    msg: "File size is {{ file_size_gb }} GB"

- name: Display total swap size
  debug:
    msg: "Total swap size is {{ swap_total_gb }} GB"

