---
- name: Supress emulation notification
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch

- name: Get users with UID > 1000
  ansible.builtin.shell: "awk -F: '$3 >= 1000 {print $1}' /etc/passwd | grep -v nobody"
  register: user_list

- name: Store users in a variable
  set_fact:
    users_above_1000: "{{ user_list.stdout_lines }}"

- name: Debug output
  debug:
    var: users_above_1000

- name: Enable linger for each user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ item }}"
  loop: "{{ users_above_1000}}"
  become: true
  changed_when: false
  ignore_errors: true

  # without loop
#- name: Enable linger for user ID 1000
  #ansible.builtin.command:
    #cmd: loginctl enable-linger 1000
  #become: true
  #changed_when: false
  #ignore_errors: true

- name: Create directories for {{ ansible_role_name }} files
  tags:
    - scripts
  ansible.builtin.file:
    path: "/home/{{ item }}{{ docker_docker_dir }}"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0775'
    recurse: yes
  loop: "{{ users_above_1000 }}"
  become: true
  #become_user: "{{ users_above_1000 }}"

- name: Create directories for {{ ansible_role_name }}-compose files
  tags:
    - scripts
  ansible.builtin.file:
    path: "/home/{{ item }}/{{ docker_compose_dir }}"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0775'
    recurse: yes
  loop: "{{ users_above_1000 }}"
  become: true
  #become_user: "{{ users_above_1000 }}"

#- name: Create directories for {{ ansible_role_name }} files
#  tags:
#    - scripts
#  ansible.builtin.file:
#    path: "{{ docker_docker_dir }}"
#    state: directory
#    owner: root
#    group: root
#    mode: 0775
#    recurse: yes
#
#- name: Create directories for {{ ansible_role_name }}-compose files
#  tags:
#    - scripts
#  ansible.builtin.file:
#    path: "{{ docker_compose_dir }}"
#    state: directory
#    owner: root
#    group: root
#    mode: 0775
#    recurse: yes

- name: Copy healthcheck_{{ ansible_role_name }}
  tags:
    - scripts
  ansible.builtin.copy:
    src: "healthcheck_{{ ansible_role_name }}"
    dest: "{{ bin_path }}/healthcheck_{{ ansible_role_name }}"
    owner: root
    group: root
    mode: '0755'

- name: Create Cronjob
  tags:
    - cron
  ansible.builtin.cron:
    name: "healthcheck_{{ ansible_role_name }}"
    minute: "*/30"
    hour: "8-21"
    job: "{{ bin_path }}/healthcheck_{{ ansible_role_name }} >/dev/null"
    user: root

- name: Copy cont command
  tags:
    - scripts
  ansible.builtin.copy:
    src: cont
    dest: "{{ bin_path }}/cont"
    owner: root
    group: root
    mode: '0755'

- name: Copy comp command
  tags:
    - scripts
  ansible.builtin.copy:
    src: comp
    dest: "{{ bin_path }}/comp"
    owner: root
    group: root
    mode: '0755'

##- name: Copy dockerrc
##  tags:
##    - scripts
##  ansible.builtin.template:
##    src: dockerrc.j2
##    dest: $HOME/.dockerrc
##    owner: root
##    group: root
##    mode: '0755'
##
##- name: Insert source command to .bashrc
##  tags:
##    - scripts
##  ansible.builtin.blockinfile:
##    path: $HOME/.bashrc
##    block: |
##      if [ -f $HOME/.dockerrc ]; then
##        . $HOME/.dockerrc
##      fi



- name: Copy dockerrc
  tags:
    - scripts
  ansible.builtin.template:
    src: dockerrc.j2
    dest: "/home/{{ item }}/.dockerrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0755'
  loop: "{{ users_above_1000 }}"
  become: true

- name: Insert source command to .bashrc
  tags:
    - scripts
  ansible.builtin.blockinfile:
    path: "/home/{{ item }}/.bashrc"
    block: |
      if [ -f $HOME/.dockerrc ]; then
        . $HOME/.dockerrc
      fi
  loop: "{{ users_above_1000 }}"
  become: true
