---
- name: Install necessary packages
  import_tasks: install.yml

- name: Configure {{ ansible_role_name }}
  tags:
    - configure
  import_tasks: configure.yml

- name: Test {{ ansible_role_name }}
  import_tasks: test.yml

