---
- name: Install podman
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
   - podman
   - podman-compose
   - podman-docker
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install podman
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - podman
   - podman-compose
   - podman-docker
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
